image: node:latest

stages:
  - deploy

before_script:
  - apt-get update -y
  - apt-get -y install rsync
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get -y install rsync
    # install deps
    - npm install
    # build frontend
    - npm run build
    # update frontend files in server
    - rsync -avz
      --delete
      $PWD/dist/ root@157.230.215.44:/var/www/html/
    # update backend dir files
    - rsync -avz
      --delete
      --exclude db
      $PWD/backend/ root@157.230.215.44:/var/www/html/backend
    # update backend entry files
    - rsync -avz
      --exclude="*"
      --include="server.js"
      --include="http-server.js"
      --include="package.json"
      --include="package-lock.json"
      $PWD/backend root@157.230.215.44:/var/www/html
    # install packages necessary for backend
    - npm install
    - ssh root@157.230.215.44 && sudo -u nodejs pm2 start server.js -- --port=8080

  artifacts:
    paths:
     - node_modules/
  environment:
    name: production
    url: https://example.com
  only:
    - master
