image: node:latest

stages:
  - deploy

before_script:
  - apt-get update -y
  - apt-get -y install rsync
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # - mkdir -p ~/.ssh
  # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get -y install rsync
    - npm install
    - npm run build
    - rsync -av --delete  "$PWD/dist" 
      root@157.230.215.44/var/www/html/
  artifacts:
    paths:
      - node_modules/
  environment:
    name: production
    url: https://example.com
  only:
    - master